# Generated by Django 3.0.6 on 2020-06-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outrights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
