# Generated by Django 3.0.6 on 2020-06-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outrights', '0003_auto_20200604_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='SterlingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20, null=True, unique=True)),
                ('h10', models.FloatField(blank=True, null=True)),
                ('m10', models.FloatField(blank=True, null=True)),
                ('u10', models.FloatField(blank=True, null=True)),
                ('z10', models.FloatField(blank=True, null=True)),
                ('h11', models.FloatField(blank=True, null=True)),
                ('m11', models.FloatField(blank=True, null=True)),
                ('u11', models.FloatField(blank=True, null=True)),
                ('z11', models.FloatField(blank=True, null=True)),
                ('h12', models.FloatField(blank=True, null=True)),
                ('m12', models.FloatField(blank=True, null=True)),
                ('u12', models.FloatField(blank=True, null=True)),
                ('z12', models.FloatField(blank=True, null=True)),
                ('h13', models.FloatField(blank=True, null=True)),
                ('m13', models.FloatField(blank=True, null=True)),
                ('u13', models.FloatField(blank=True, null=True)),
                ('z13', models.FloatField(blank=True, null=True)),
                ('h14', models.FloatField(blank=True, null=True)),
                ('m14', models.FloatField(blank=True, null=True)),
                ('u14', models.FloatField(blank=True, null=True)),
                ('z14', models.FloatField(blank=True, null=True)),
                ('h15', models.FloatField(blank=True, null=True)),
                ('m15', models.FloatField(blank=True, null=True)),
                ('u15', models.FloatField(blank=True, null=True)),
                ('z15', models.FloatField(blank=True, null=True)),
                ('h16', models.FloatField(blank=True, null=True)),
                ('m16', models.FloatField(blank=True, null=True)),
                ('u16', models.FloatField(blank=True, null=True)),
                ('z16', models.FloatField(blank=True, null=True)),
                ('h17', models.FloatField(blank=True, null=True)),
                ('m17', models.FloatField(blank=True, null=True)),
                ('u17', models.FloatField(blank=True, null=True)),
                ('z17', models.FloatField(blank=True, null=True)),
                ('h18', models.FloatField(blank=True, null=True)),
                ('m18', models.FloatField(blank=True, null=True)),
                ('u18', models.FloatField(blank=True, null=True)),
                ('z18', models.FloatField(blank=True, null=True)),
                ('h19', models.FloatField(blank=True, null=True)),
                ('m19', models.FloatField(blank=True, null=True)),
                ('u19', models.FloatField(blank=True, null=True)),
                ('z19', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
